version: '3'
services: 
  dev:
    user: vscode
    build: .
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SecurePwdGoesHere
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/devcert.pfx
      - DOTNET_ENVIRONMENT=Development
      - DOTNET_NOLOGO=1
    volumes: 
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    ports: 
      - 5000:5000
      - 5001:5001
